name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # Checkout Code
      # =========================
      - name: Checkout
        uses: actions/checkout@v4


      # =========================
      # Setup Node
      # =========================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      # =========================
      # Install Dependencies
      # =========================
      - name: Install Dependencies
        run: npm install


      # =========================
      # Build Next.js
      # =========================
      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}


      # =========================
      # Deploy Production
      # =========================
      - name: Deploy Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
