name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # Checkout Repository
      # =========================
      - name: Checkout
        uses: actions/checkout@v4


      # =========================
      # Setup Node LTS
      # =========================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      # =========================
      # Install Dependencies
      # =========================
      - name: Install Dependencies
        run: npm install


      # =========================
      # Build Next.js
      # =========================
      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}


      # =========================
      # Install Latest Vercel CLI
      # =========================
      - name: Install Vercel CLI
        run: npm install -g vercel@latest


      # =========================
      # Deploy Production
      # =========================
      - name: Deploy Vercel Production
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
